;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Tue Sep 30 2025
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

DATA SEGMENT 
    PORTA EQU 0F0H ; PORTA address 
    PORTB EQU 0F2H ; PORTB address 
    PORTC EQU 0F4H ; PORTC address 
DATA ENDS 

CODE SEGMENT PUBLIC 'CODE'
    ASSUME CS:CODE, DS:DATA
    MOV AX, DATA
    MOV DS, AX
    ORG 0000H

START:
    MOV DX, PORTC
    IN  AL, DX

    cmp al, 00000000b
    je OFF_SEG
    
    cmp al, 00000001b
    je COUNT_SEG

    ;cmp al, 00010001b 
    ;je COUNT_LED 
    
    cmp al, 00010001b 
    je ONE
    
    cmp al, 00100001b 
    je TWO 
    
    cmp al, 00110001b 
    je THREE 
    
    cmp al, 01000001b 
    je FOUR 
    
    cmp al, 01010001b 
    je FIVE 
    
    cmp al, 01100001b 
    je SIX 
    
    cmp al, 01110001b 
    je SEVEN 
    
    cmp al, 10000001b 
    je EIGHT 
    
    cmp al, 10010001b 
    je NINE 
    
    JMP START

COUNT_SEG:
    MOV DX, PORTB
    MOV AL, 00111111B ;0
    OUT DX, AL
    
    MOV DX, PORTA
    MOV AL, 0000b
    OUT DX, AL
    
    CALL DELAY_1MS

    
    ONE:
    MOV DX, PORTB
    MOV AL, 00000110B ;1
    OUT DX, AL
    
    MOV DX, PORTA
    MOV AL, 0001b
    OUT DX, AL
    
    CALL DELAY_1MS

    TWO:
    MOV DX, PORTB
    MOV AL, 01011011B ;2
    OUT DX, AL
    
    MOV DX, PORTA
    MOV AL, 0010b
    OUT DX, AL
    
    CALL DELAY_1MS

    THREE:
    MOV DX, PORTB
    MOV AL, 01001111B ;3
    OUT DX, AL
    
    MOV DX, PORTA
    MOV AL, 0011b
    OUT DX, AL
    
    CALL DELAY_1MS

    FOUR:
    MOV DX, PORTB
    MOV AL, 01100110B ;4
    OUT DX, AL
    
    MOV DX, PORTA
    MOV AL, 0100b
    OUT DX, AL
    
    CALL DELAY_1MS

    FIVE:
    MOV DX, PORTB
    MOV AL, 01101101B ;5
    OUT DX, AL
    MOV DX, PORTA
    MOV AL, 0101b
    OUT DX, AL
    CALL DELAY_1MS

    SIX:
    MOV DX, PORTB
    MOV AL, 01111101B ;6
    OUT DX, AL
    MOV DX, PORTA
    MOV AL, 0110b
    OUT DX, AL
    CALL DELAY_1MS

    SEVEN:
    MOV DX, PORTB
    MOV AL, 00000111B ;7
    OUT DX, AL
    MOV DX, PORTA
    MOV AL, 0111b
    OUT DX, AL
    CALL DELAY_1MS

    EIGHT:
    MOV DX, PORTB
    MOV AL, 01111111B ;8
    OUT DX, AL
    MOV DX, PORTA
    MOV AL, 1000b
    OUT DX, AL
    CALL DELAY_1MS

    NINE:
    MOV DX, PORTB
    MOV AL, 01101111B ;9
    OUT DX, AL
    MOV DX, PORTA
    MOV AL, 1001b
    OUT DX, AL
    CALL DELAY_1MS
    
    
    ;MOV AL, 00111111B ;0
    ;OUT DX, AL
    
    JMP START
    
    OFF_SEG:
    MOV DX, PORTB
    MOV AL, 00000000B ;0
    OUT DX, AL
    CALL DELAY_1MS
    
    JMP START

DELAY_1MS:
    MOV BX, 9H
L1:
    DEC BX
    NOP
    JNZ L1
    RET

CODE ENDS
END START
