;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Tue Sep 30 2025
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

DATA SEGMENT 
   PORTA EQU 0F0H
   PORTB EQU 0F2H 
   PORTC EQU 0F4H
DATA ENDS 

CODE SEGMENT PUBLIC 'CODE'
    ASSUME CS:CODE, DS:DATA
    MOV AX, DATA
    MOV DS, AX
    ORG 0000H

START:

   MOV DX, PORTB
   MOV AL,  0111111B
   OUT DX, AL
   MOV DX, PORTA
   MOV AL, 0000H
   OUT DX, AL

HERE:
   MOV  DX, PORTC
   IN  AL, DX
   TEST AL, 01H
   JZ HERE
   
   MOV DX, PORTC
   IN  AL, DX
   MOV CL, 4
   SHR AL, CL
   MOV DX, PORTA
   OUT DX, AL  
   
   CMP  AL, 0
   JE ZERO
   
   CMP AL, 1
   JE ONE
   
   CMP AL, 2
   JE TWO
   
   CMP AL, 3
   JE THREE
   
   CMP AL, 4
   JE FOUR
   
   CMP AL, 5
   JE FIVE
   
   CMP AL, 6
   JE SIX
   
   CMP AL, 7
   JE SEVEN 
   
   CMP AL, 8
   JE EIGHT
   
   CMP AL, 9
   JE NINE

   
ZERO:
   MOV DX, PORTB
   MOV AL,  0111111B
   OUT DX, AL
   JMP HERE 
   
ONE:
   MOV DX, PORTB
   MOV AL, 0000110B
   OUT DX, AL
   JMP HERE   
 
TWO:
   MOV DX, PORTB
   MOV AL,  1011011B
   OUT DX, AL
   JMP HERE
   
THREE:
   MOV DX, PORTB
   MOV AL, 1001111B
   OUT DX, AL
   JMP HERE  
   
FOUR:
   MOV DX, PORTB
   MOV AL, 1100110B
   OUT DX, AL
   JMP HERE

FIVE:
   MOV DX, PORTB
   MOV AL,1101101B
   OUT DX, AL
   JMP HERE
   
SIX:
   MOV DX, PORTB
   MOV AL, 1111101B
   OUT DX, AL
   JMP HERE
   
SEVEN: 
   MOV DX, PORTB
   MOV AL, 0000111B
   OUT DX, AL
   JMP HERE

EIGHT: 
   MOV DX, PORTB
   MOV AL,1111111B
   OUT DX, AL
   JMP HERE  
   
NINE: 
   MOV DX, 0F2H
   MOV AL, 1101111B
   OUT DX, AL
   JMP HERE  
   
;ENDLESS:
   ;JMP ENDLESS

CODE ENDS
END START
