DATA SEGMENT
    ; 8255A I/O Interface Mappings
    LCD_PORTA      EQU 0F0H
    LCD_PORTB      EQU 0F2H
    KEYPAD_PORT    EQU 0F4H
    CONTROL_PORT   EQU 0F6H

    ; Keypad Mappings
    KEY_1          EQU 00H
    KEY_2          EQU 01H
    KEY_0          EQU 0DH
    KEY_STAR       EQU 0CH
    KEY_HASH       EQU 0EH

    ; LCD Display Text
    TXT_HEADER         DB 'HOME MENU ', '$'
    TXT_OPTION_CODE    DB '[1] Set Code ', '$'
    TXT_OPTION_ARM     DB '[2] Arm System  ', '$'
    TXT_PROMPT_SELECT  DB 'Choice?', '$'
    TXT_PROMPT_CODE    DB 'Input Code:', '$'
    TXT_NO_PASSKEY     DB 'No Key Stored!', '$'
    TXT_ARMED          DB 'WARNING: System is armed!', '$'
    TXT_INSTR_DISARM   DB 'Press 0 to disable', '$'
    TXT_INACTIVE       DB 'SUCCESS: System is disarmed!', '$'
    TXT_RETURN_MENU    DB 'Press # to return', '$'
    TXT_WRONG_KEY      DB 'Invalid Entry!', '$'
    TXT_SHORT_KEY      DB 'Key Too Short!', '$'

    ; System Data Memory
    STORED_KEY      DB 8 DUP(0)
    TEMP_INPUT      DB 8 DUP(0)
    KEY_SIZE        DB 0
    IS_KEY_STORED   DB 0
DATA ENDS


CODE SEGMENT PUBLIC 'CODE'
    ASSUME CS:CODE, DS:DATA

MAIN:
    MOV AX, DATA
    MOV DS, AX

    ; Initialize I/O Controller
    MOV DX, CONTROL_PORT
    MOV AL, 10001001B
    OUT DX, AL
    CALL INIT_LCD

; ============ SYSTEM INITIALIZATION ============
SYSTEM_START:
    CALL CLEAR_LCD

WAIT_POWER_KEY:
    MOV DX, KEYPAD_PORT
    IN AL, DX
    TEST AL, 00010000B
    JZ WAIT_POWER_KEY

    IN AL, DX
    AND AL, 00001111B
    CMP AL, KEY_STAR
    JNE WAIT_POWER_KEY

    CALL DELAY_3SEC
    MOV DX, KEYPAD_PORT
    IN AL, DX
    AND AL, 00001111B
    CMP AL, KEY_STAR
    JNE WAIT_POWER_KEY

    JMP SHOW_MENU

; ============ MAIN MENU ============
SHOW_MENU:
    CALL CLEAR_LCD
    
    ; Line 1: Title
    MOV AL, 10000000B
    CALL LCD_CMD
    LEA SI, TXT_HEADER
    CALL PRINT_TEXT

    ; Line 2: Option 1
    MOV AL, 11000000B
    CALL LCD_CMD
    LEA SI, TXT_OPTION_CODE
    CALL PRINT_TEXT

    ; Line 3: Option 2
    MOV AL, 10010100B
    CALL LCD_CMD
    LEA SI, TXT_OPTION_ARM
    CALL PRINT_TEXT

    ; Line 4: Prompt
    MOV AL, 11010100B
    CALL LCD_CMD
    LEA SI, TXT_PROMPT_SELECT
    CALL PRINT_TEXT

GET_USER_SELECTION:
    MOV DX, KEYPAD_PORT
    IN AL, DX
    TEST AL, 00010000B
    JZ GET_USER_SELECTION

    IN AL, DX
    AND AL, 00001111B
    PUSH AX

    CMP AL, KEY_HASH
    JE HOLD_HASH_CHECK

WAIT_FOR_RELEASE:
    MOV DX, KEYPAD_PORT
    IN AL, DX
    TEST AL, 00010000B
    JNZ WAIT_FOR_RELEASE

    POP AX
    CMP AL, KEY_1
    JE DEFINE_KEY
    CMP AL, KEY_2
    JE ENABLE_ALARM

    JMP GET_USER_SELECTION

HOLD_HASH_CHECK:
    POP AX
    CALL DELAY_5SEC
    MOV DX, KEYPAD_PORT
    IN AL, DX
    AND AL, 00001111B
    CMP AL, KEY_HASH
    JNE SHOW_MENU
    JMP SYSTEM_START

; ============ FUNCTION ROUTES ============
DEFINE_KEY:
    CALL SET_PASSCODE
    JMP SHOW_MENU

ENABLE_ALARM:
    CMP IS_KEY_STORED, 0
    JE SHOW_NO_KEY
    CALL DISPLAY_ARMED

WAIT_FOR_ZERO:
    CALL READ_KEY
    CMP AL, KEY_0
    JNE WAIT_FOR_ZERO
    CALL DISABLE_ALARM
    JMP SHOW_MENU

SHOW_NO_KEY:
    CALL NO_KEY_ALERT
    JMP SHOW_MENU

; ============ LCD HANDLING ============
CLEAR_LCD:
    MOV AL, 00000001B
    CALL LCD_CMD
    CALL DELAY_1MS
    CALL DELAY_1MS
    RET

LCD_CMD:
    PUSH AX
    PUSH BX
    MOV DX, LCD_PORTA
    OUT DX, AL
    MOV DX, LCD_PORTB
    MOV AL, 00000010B
    OUT DX, AL
    CALL DELAY_1MS
    MOV DX, LCD_PORTB
    MOV AL, 00000000B
    OUT DX, AL
    POP BX
    POP AX
    RET

LCD_CHAR:
    PUSH AX
    PUSH BX
    MOV DX, LCD_PORTA
    OUT DX, AL
    MOV DX, LCD_PORTB
    MOV AL, 00000011B
    OUT DX, AL
    CALL DELAY_1MS
    MOV DX, LCD_PORTB
    MOV AL, 00000001B
    OUT DX, AL
    POP BX
    POP AX
    RET

INIT_LCD:
    MOV AL, 00111000B
    CALL LCD_CMD
    MOV AL, 00001000B
    CALL LCD_CMD
    MOV AL, 00000001B
    CALL LCD_CMD
    MOV AL, 00000110B
    CALL LCD_CMD
    MOV AL, 00001100B
    CALL LCD_CMD
    RET

PRINT_TEXT:
    MOV AL, [SI]
    CMP AL, '$'
    JE DONE_TEXT
    CALL LCD_CHAR
    INC SI
    JMP PRINT_TEXT
DONE_TEXT:
    RET

; ============ KEYPAD HANDLING ============
READ_KEY:
CHECK_PRESS:
    MOV DX, KEYPAD_PORT
    IN AL, DX
    TEST AL, 00010000B
    JZ CHECK_PRESS
    IN AL, DX
    AND AL, 00001111B
    PUSH AX
WAIT_RELEASE:
    MOV DX, KEYPAD_PORT
    IN AL, DX
    TEST AL, 00010000B
    JNZ WAIT_RELEASE
    POP AX
    RET

; ============ TIME DELAYS ============
DELAY_1MS:
    MOV BX, 02CAH
LOOP_1MS:
    DEC BX
    NOP
    JNZ LOOP_1MS
    RET

DELAY_100MS:
    PUSH CX
    MOV CX, 100
LOOP_100MS:
    CALL DELAY_1MS
    LOOP LOOP_100MS
    POP CX
    RET

DELAY_200MS:
    PUSH CX
    MOV CX, 2
LOOP_200MS:
    CALL DELAY_100MS
    LOOP LOOP_200MS
    POP CX
    RET

DELAY_2SEC:
    PUSH CX
    MOV CX, 10
LOOP_2S:
    CALL DELAY_100MS
    LOOP LOOP_2S
    POP CX
    RET

DELAY_3SEC:
    PUSH CX
    MOV CX, 8
LOOP_3S:
    CALL DELAY_100MS
    LOOP LOOP_3S
    POP CX
    RET

DELAY_5SEC:
    PUSH CX
    MOV CX, 11
LOOP_5S:
    CALL DELAY_100MS
    LOOP LOOP_5S
    POP CX
    RET

; ============ ALERT MESSAGES ============
NO_KEY_ALERT:
    MOV CX, 3
BLINK_NO_KEY:
    CALL CLEAR_LCD
    MOV AL, 10000000B
    CALL LCD_CMD
    LEA SI, TXT_NO_PASSKEY
    CALL PRINT_TEXT
    CALL DELAY_200MS
    CALL CLEAR_LCD
    CALL DELAY_200MS
    LOOP BLINK_NO_KEY
    RET

DISPLAY_ARMED:
    MOV CX, 3
ARM_LOOP:
    CALL CLEAR_LCD
    MOV AL, 10000000B
    CALL LCD_CMD
    LEA SI, TXT_ARMED
    CALL PRINT_TEXT
    MOV AL, 11000000B
    CALL LCD_CMD
    LEA SI, TXT_INSTR_DISARM
    CALL PRINT_TEXT
    CALL DELAY_200MS
    CALL CLEAR_LCD
    CALL DELAY_200MS
    LOOP ARM_LOOP

    CALL CLEAR_LCD
    MOV AL, 10000000B
    CALL LCD_CMD
    LEA SI, TXT_ARMED
    CALL PRINT_TEXT
    MOV AL, 11000000B
    CALL LCD_CMD
    LEA SI, TXT_INSTR_DISARM
    CALL PRINT_TEXT
    RET

; ============ CORE FEATURES ============
SET_PASSCODE:
    CALL CLEAR_LCD
    MOV AL, 10000000B
    CALL LCD_CMD
    LEA SI, TXT_PROMPT_CODE
    CALL PRINT_TEXT
    MOV AL, 11000000B
    CALL LCD_CMD

    LEA DI, STORED_KEY
    MOV BH, 0

INPUT_KEY:
    CALL READ_KEY
    CMP AL, KEY_HASH
    JE FINISH_INPUT
    CMP BH, 8
    JE INPUT_KEY
    MOV [DI], AL
    INC DI
    INC BH
    MOV AL, '*'
    CALL LCD_CHAR
    JMP INPUT_KEY

FINISH_INPUT:
    CMP BH, 4
    JB TOO_SHORT
    MOV IS_KEY_STORED, 1
    MOV KEY_SIZE, BH
    RET

TOO_SHORT:
    CALL CLEAR_LCD
    MOV AL, 10000000B
    CALL LCD_CMD
    LEA SI, TXT_SHORT_KEY
    CALL PRINT_TEXT
    CALL DELAY_2SEC
    RET

DISABLE_ALARM:
    CALL CLEAR_LCD
    MOV AL, 10000000B
    CALL LCD_CMD
    LEA SI, TXT_PROMPT_CODE
    CALL PRINT_TEXT

VERIFY_START:
    MOV AL, 11000000B
    CALL LCD_CMD
    LEA DI, TEMP_INPUT
    MOV BH, 0

READ_VERIFY:
    CALL READ_KEY
    CMP AL, KEY_HASH
    JE CHECK_MATCH
    MOV DL, KEY_SIZE
    CMP BH, DL
    JE READ_VERIFY
    MOV [DI], AL
    INC DI
    INC BH
    MOV AL, '*'
    CALL LCD_CHAR
    JMP READ_VERIFY

CHECK_MATCH:
    MOV DL, KEY_SIZE
    CMP BH, DL
    JNE WRONG_KEY
    LEA SI, STORED_KEY
    LEA DI, TEMP_INPUT
    MOV CL, KEY_SIZE
    MOV CH, 0

COMPARE_INPUTS:
    MOV AL, [SI]
    MOV DL, [DI]
    CMP AL, DL
    JNE WRONG_KEY
    INC SI
    INC DI
    LOOP COMPARE_INPUTS

    CALL CLEAR_LCD
    MOV AL, 10000000B
    CALL LCD_CMD
    LEA SI, TXT_INACTIVE
    CALL PRINT_TEXT
    MOV AL, 11000000B
    CALL LCD_CMD
    LEA SI, TXT_RETURN_MENU
    CALL PRINT_TEXT

WAIT_HASH_RETURN:
    CALL READ_KEY
    CMP AL, KEY_HASH
    JNE WAIT_HASH_RETURN
    RET

WRONG_KEY:
    CALL CLEAR_LCD
    MOV AL, 10000000B
    CALL LCD_CMD
    LEA SI, TXT_WRONG_KEY
    CALL PRINT_TEXT
    CALL DELAY_2SEC
    JMP DISABLE_ALARM

CODE ENDS
END MAIN
